AWSTemplateFormatVersion: '2010-09-09'
Description: AWS App Runner Service for DevSecOps Project with ECR, IAM, and CloudWatch Alarms

Parameters:
  EcrImageUri:
    Type: String
    Description: URI of the ECR image pushed by the build stage (e.g., <account_id>.dkr.ecr.<region>.amazonaws.com/repo-name:tag)

Resources:
  AppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: devsecops-zap-app-repo
      ImageScanningConfiguration:
        scanOnPush: true

  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ 'build.apprunner.amazonaws.com' ]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECR
      Path: /
      RoleName: devsecops-AppRunnerAccessRole

  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: devsecops-zap-app
      Description: Latest deployment for DevSecOps pipeline
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: !Ref EcrImageUri
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: '8080'
            RuntimeEnvironmentVariables:
              NODE_ENV: production
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerAccessRole.Arn
      InstanceConfiguration:
        Cpu: '1024'
        Memory: '2048'
      HealthCheckConfiguration:
        Path: /health
        Protocol: HTTP
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5
      ObservabilityConfiguration:
        ObservabilityEnabled: true

  AppRunnerHighCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: devsecops-High-CPU-Usage
      AlarmDescription: "Alarm triggered if App Runner CPU utilization exceeds 80% for 3 minutes"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: 60
      Statistic: Average
      Threshold: 80
      Namespace: AWS/AppRunner
      MetricName: CpuUtilization
      Dimensions:
        - Name: ServiceId
          Value: !GetAtt AppRunnerService.ServiceId

  AppRunnerServerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: devsecops-Server-Error-Rate
      AlarmDescription: "Alarm triggered if 5xx HTTP errors occur."
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      Namespace: AWS/AppRunner
      MetricName: 5xxResponse
      Dimensions:
        - Name: ServiceId
          Value: !GetAtt AppRunnerService.ServiceId

Outputs:
  ServiceUrl:
    Description: The live URL of the deployed App Runner Service
    Value: !GetAtt AppRunnerService.ServiceUrl
    Export:
      Name: devsecops-ServiceUrl
