AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack for deploying ZAP Proxy with AWS App Runner

Resources:
  # IAM Role for App Runner to access ECR
  AppRunnerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  # App Runner Service
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: zap-proxy-service
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: 
            Fn::GetAtt: [AppRunnerServiceRole, Arn]
        ImageRepository:
          ImageIdentifier: 879381264902.dkr.ecr.us-east-1.amazonaws.com/devsecops-zap-app-repo:76a32a2fbb205544abcccbd5a3e3fca2a7e0520e
          ImageRepositoryType: ECR
        AutoDeploymentsEnabled: true
      InstanceConfiguration:
        Cpu: 1024
        Memory: 2048
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5
      ObservabilityConfiguration:
        ObservabilityEnabled: false

Outputs:
  ServiceUrl:
    Description: "App Runner Service URL"
    Value: 
      Fn::GetAtt: [AppRunnerService, ServiceUrl]
