# infra/cloudformation/apprunner-template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Description: AWS App Runner Service for DevSecOps Project (Container Deployment)

Parameters:
  # This parameter will be passed by the GitHub Actions pipeline during deployment
  EcrImageUri:
    Type: String
    Description: URI of the ECR image pushed by the build stage (e.g., <account_id>.dkr.ecr.<region>.amazonaws.com/repo-name:tag)

Resources:
  # 1. AWS ECR Repository to store the Docker image 
  AppEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: devsecops-zap-app-repo
      ImageScanningConfiguration:
        ScanOnPush: true 

  # 2. IAM Role for App Runner to securely pull images from ECR
  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ 'build.apprunner.amazonaws.com' ]
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECR
      Path: /
      RoleName: devsecops-AppRunnerAccessRole

  # 3. AWS App Runner Service to deploy the container
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: devsecops-zap-app
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: !Ref EcrImageUri # The Image URI passed as a parameter
          ImageRepositoryType: ECR 
          ImageConfiguration:
            Port: '8080' # Must match the EXPOSE port in your app/Dockerfile
            RuntimeEnvironmentVariables:
              NODE_ENV: production
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerAccessRole.Arn
      
      HealthCheckConfiguration:
        Path: /health # Matches the health endpoint in app/server.js

Outputs:
  ServiceUrl:
    Description: The live URL of the deployed App Runner Service
    Value: !GetAtt AppRunnerService.ServiceUrl
    Export:
      Name: devsecops-ServiceUrl

  EcrRepositoryUri:
    Description: ECR Repository URI (used by the pipeline)
    Value: !GetAtt AppEcrRepository.RepositoryUri
    Export:
      Name: devsecops-EcrRepositoryUri